#### <font color='LightCoral'> **ЗАДАНИЕ 32.** Структуры данных: массивы.

8. Используя модуль `array` и  библиотеку `numpy`, решить следующие задачи:<br>а) Дан массив $A$ размера $N$. Сформировать новый массив B того же размера по следующему правилу: элемент BK равен сумме элементов массива $A$ с номерами от 1 до $K$.<br>б) Дана матрица размера $M×N$. Элемент матрицы называется ее локальным минимумом, если он меньше всех окружающих его элементов. Заменить все локальные минимумы данной матрицы на нули.

In [1]:
# A
import numpy as np

def generate_array_B(A):
    B = np.zeros_like(A)  # Создаем массив B с нулевыми значениями и такой же формой, как и A
    for k in range(len(A)):
        B[k] = np.sum(A[:k+1])  # Суммируем элементы A с индексами от 0 до k и записываем в B[k]
    return B

# Пример использования:
A = np.array([1, 2, 3, 4, 5])
B = generate_array_B(A)
print("Массив A:", A)
print("Массив B:", B)


Массив A: [1 2 3 4 5]
Массив B: [ 1  3  6 10 15]


In [9]:
# B
import numpy as np

def replace_local_minima(matrix):
    M, N = matrix.shape
    for i in range(1, M - 1):
        for j in range(1, N - 1):
            if matrix[i, j] < min(matrix[i-1,j-1],matrix[i-1,j+1],matrix[i+1,j-1],matrix[i+1,j+1]):  # Проверяем, является ли элемент матрицы локальным минимумом
                matrix[i, j] = 0  # Если да, заменяем его на ноль
    return matrix

# Пример использования:
matrixtest = np.array([[2, 2, 3],
                   [4, -1, 5],
                   [6, 7, 2]])

print("Исходная матрица:")
print(matrixtest)

result_matrix = replace_local_minima(matrixtest)
print("Матрица после замены локальных минимумов на нули:")
print(result_matrix)

Исходная матрица:
[[ 2  2  3]
 [ 4 -1  5]
 [ 6  7  2]]
Матрица после замены локальных минимумов на нули:
[[2 2 3]
 [4 0 5]
 [6 7 2]]


#### <font color='LightCoral'> **ЗАДАНИЕ 33.** Структуры данных: стек.

8. Дан стек. Необходимо проверить, является ли его содержимое палиндромом (то есть читается одинаково как слева направо, так и справа налево).

In [10]:
class Stack:
    def __init__(self):
        self.items = []

    def push(self, item):
        self.items.append(item)

    def pop(self):
        return self.items.pop()

    def is_empty(self):
        return len(self.items) == 0

    def peek(self):
        if not self.is_empty():
            return self.items[-1]
        else:
            return None

def is_palindrome(stack):
    reversed_stack = Stack()  # Создаем пустой стек для хранения элементов в обратном порядке
    original_stack = stack  # Копируем исходный стек

    # Переносим элементы из исходного стека в обратном порядке в reversed_stack
    while not original_stack.is_empty():
        reversed_stack.push(original_stack.pop())

    # Сравниваем элементы исходного стека с элементами reversed_stack
    while not stack.is_empty():
        if stack.pop() != reversed_stack.pop():
            return False  # Если элементы не совпадают, стек не является палиндромом
    return True  # Если все элементы совпадают, стек является палиндромом

# Пример использования:
s = Stack()
s.push(1)
s.push(2)
s.push(3)
s.push(2)
s.push(1)

print("Содержимое стека:", s.items)

if is_palindrome(s):
    print("Стек является палиндромом")
else:
    print("Стек не является палиндромом")


Содержимое стека: [1, 2, 3, 2, 1]
Стек является палиндромом


#### <font color='LightCoral'> **ЗАДАНИЕ 34.** Структуры данных: очередь.

8. Создать класс двусторонней очереди, который будет поддерживать операции добавления элемента в начало и конец очереди, удаления элемента из начала и конца очереди, а также удаления минимального и максимального элементов из очереди.

In [11]:
from collections import deque

class MinMaxDeque:
    def __init__(self):
        self.deque = deque()
        self.min_max_deque = deque()

    def add_front(self, item):
        self.deque.appendleft(item)
        while self.min_max_deque and self.min_max_deque[-1] > item:
            self.min_max_deque.pop()
        self.min_max_deque.append(item)

    def add_rear(self, item):
        self.deque.append(item)
        while self.min_max_deque and self.min_max_deque[-1] > item:
            self.min_max_deque.pop()
        self.min_max_deque.append(item)

    def remove_front(self):
        if not self.deque:
            return None
        item = self.deque.popleft()
        if item == self.min_max_deque[0]:
            self.min_max_deque.popleft()
        return item

    def remove_rear(self):
        if not self.deque:
            return None
        item = self.deque.pop()
        if item == self.min_max_deque[-1]:
            self.min_max_deque.pop()
        return item

    def remove_min(self):
        if not self.deque:
            return None
        return self.remove_front()

    def remove_max(self):
        if not self.deque:
            return None
        return self.remove_rear()

    def __str__(self):
        return str(self.deque)

# Пример использования:
d = MinMaxDeque()
d.add_front(5)
d.add_rear(10)
d.add_front(3)
d.add_rear(15)
print("Двусторонняя очередь:", d)

print("Удаление минимального элемента:", d.remove_min())
print("Удаление максимального элемента:", d.remove_max())
print("После удаления минимального и максимального элементов:", d)


Двусторонняя очередь: deque([3, 5, 10, 15])
Удаление минимального элемента: 3
Удаление максимального элемента: 15
После удаления минимального и максимального элементов: deque([5, 10])
